### ISSUE TITLE
Consider shipping this with Fiji by default

### ISSUE THREAD

**Issue by imagejan** [BIOP/ijp-siftalignmultichannel-ij2#1]
... and migrating it to the `fiji` GitHub org, (maybe renaming it -- what's the `ij2` in the name, by the way?),
... and deploying a maven artifact to maven.scijava.org 😉

**Comment by NicoKiaru** [comment]
Sure, of course.

> what's the ij2 in the name, by the way ?

Ah yes! No idea why it got there.

> ... and migrating it to the fiji GitHub org

That's the **option 1**. But maybe there's another option:

I made with @romainGuiet some time ago a  [PR](https://github.com/axtimwalde/mpicbg/pull/55)  to **modify** the original plugin https://github.com/axtimwalde/mpicbg/blob/master/mpicbg_/src/main/java/SIFT_Align.java, but closed it to make this repo. Indeed modifying the original repo may not be a good idea because it could break other people's scripts.

However, the **option 2** would be, not to modify, but to **add** side to side this plugin to the original plugin https://github.com/axtimwalde/mpicbg/blob/master/mpicbg_/src/main/java/SIFT_Align.java repo. 

Please @axtimwalde let us know if option 2 seems ok to you. If you prefer that we don't add anything to the original repo, then we'll probably go for option 1

**Comment by axtimwalde** [comment]
Option 2 sounds good!

**Comment by NicoKiaru** [comment]
PR done!

**Comment by imagejan** [comment]
With https://github.com/axtimwalde/mpicbg/pull/62, this is now in `mpicbg-1.5.0` and later.

I suggest archiving this repository here.
